#Numpy

* numpy is a multdin array

In [16]:

import numpy as np

#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [17]:
import numpy as np


#THE BASICS :

#initialize array

In [18]:
#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [ ]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [20]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)


dimension of a : 1
dimension of b : 2


In [21]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


In [22]:

#Get  Type
print("a type is :",a.dtype)

#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

a type is : int16
size of a : 3


In [23]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)


a item size : 2
total size is a: 6


In [24]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]


np.float64(4.2)

In [25]:
b

array([[1. , 2. , 3. , 5.8],
       [2.1, 3. , 4.2, 4.5]])

In [26]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);


row : [2.1]


In [27]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [28]:

#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [30]:

#change element
b[1,2]=8
print(b)

[[1.  2.  9.  5.8]
 [2.1 3.  8.  4.5]]


In [29]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [31]:
b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [32]:
int(1.2)

1

# 3-d example

In [33]:
c=np.array([
    [
    [1,2],[3,4]
],
[
 [5,6],[7,8]

]

])

In [34]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
type(c)

numpy.ndarray

In [36]:
c.ndim

3

In [37]:
c.shape

(2, 2, 2)

In [38]:
c.size

8

## calculate the memory space took for c numpy arry

In [39]:
c.dtype

dtype('int64')

In [40]:
c.itemsize *c.size

64

In [41]:
#get specific element (work outside in)
print("specified element is :",c[0,1,0])

specified element is : 3


In [42]:
#get specific element (work outside in)
print("specified element is :",c[0,0,1])

specified element is : 2


In [43]:

#get specific element (work outside in)
print("specified element is :",c[1,1,1])




specified element is : 8


In [46]:
c[1,1,1] =100
c

array([[[  1,   2],
        [  3,   4]],

       [[  5,   6],
        [  7, 100]]])

# Initializing different types of arrays

In [2]:
import numpy as np

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
zm = np.zeros((3,4))

In [5]:
zm.ndim

2

In [6]:
zm.shape

(3, 4)

# all 1's matrix

In [7]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones = np.ones((3,3),dtype="int16")

In [11]:
ones[1,1] =100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1]], dtype=int16)

In [15]:
# any other number
np.full(ones.shape,88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [16]:
#any other number
np.full((4,5),100,dtype="float")

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

#### reuse  the already existing array and assign one value to 

In [17]:
np.full_like(ones,200,dtype="float")

array([[200., 200., 200.],
       [200., 200., 200.],
       [200., 200., 200.]])

#### random matrix

In [18]:
np.random.random_sample((2,3))

array([[0.40161182, 0.78249332, 0.83104548],
       [0.10538529, 0.67924538, 0.47378341]])

In [19]:
np.random.rand(2,4)

array([[0.04807579, 0.54535387, 0.81307641, 0.67454541],
       [0.58967172, 0.75868498, 0.46527575, 0.42955807]])

In [20]:
np.random.randint(2,9,size=(3,3))

array([[8, 6, 8],
       [3, 4, 6],
       [5, 7, 8]], dtype=int32)

In [ ]:
# generate ientity matrix  only one argument bcoz identity matix is a
np.identity(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.identity(2) 

array([[1., 0.],
       [0., 1.]])